### ISSUE TITLE
MODULE 2 DELETION

### ISSUE THREAD

**Issue by enrique-lovera** [rslim087a/Java-Bootcamp-Resources#2]
Why are the module 2 deleted :( ?

**Comment by rslim087a** [comment]
What do you mean Enrique? Some files were deleted and replaced by others as part of the course update.

**Comment by enrique-lovera** [comment]
For example i can't see the top workbooks code for the MODULE 2 eg : 7.1 and so on. also i checked the last commit was the deletion of those files, probably i'm getting confused ? could you help me understand! thanks in advance ! loving the course so far !!!

**Comment by rslim087a** [comment]
No problem! They should be inside the folder: 'airline-reservation-system'. I will update the folder structure to make it more clear.

**Comment by enrique-lovera** [comment]
Thank you so much! closing this!
